var sober = ["What object, person, animal or situation is happiness? What about grief? Hope? (Emily Dickinson thought it was 'the thing with feathers ...') How about fear?",
"What dream have you never forgotten and why do you think this remains a conscious memory?",
"What olympic event would you do, if you could do any, no previous experience or talent required?",
"What is your most memorable experience involving an animal?",
"I learned a while back that they have figured out how to cremate someone and put their ashes into a vinyl record. So if you had to be turned into a vinyl record, what album or what songs would you want to be on the record?",
"Tell me about a person that you met and who is not related to you, that really made an impact on you, and/or was memorable.",
"When were you sure a bad outcome would be your ruin, but in fact it turned out to your benefit? Was it because you turned lemons into lemonade, or was it due to luck/grace/karma?",
"What is a food you’ve tried lately that you really liked?",
"If you could erase from your brain one piece of knowledge (memory, or fact/set of facts) what would it be?",
"If you could travel anywhere tomorrow, where would you go?",
"If you could be part of any world record, what would it be?",
"Tell a lie and a true thing about yourself. Let others guess which is which.",
"If you were alive in [time period X], what do you think your line of work would have been or how would you have earned a living?",
"What would (for example) my dentist be doing in the 14th Century? Or a software coder in the Wild West? An avionics engineer in Ancient Egypt? Fish out of temporal waters.",
"What is your most trivial, useless, or flat-out counter-productive superpower?",
"If you were a boat, what kind of boat would you be? And why?",
"What’s your favorite-ever celebrity sighting? (And related follow-up: Have you ever been truly star-struck?)",
"What is your most vivid memory of a historical event that occurred during your childhood?",
"Every year when I teach identity politics I ask the same question on the first day of class. Rather than the usual icebreakers, I ask: ‘How does your family / your culture cook rice?",
"What was your favorite activity as a 10-year-old?",
"What activities, realizations, or new ways of doing things will you (try to) keep from this past year?",
"What is the dumbest thing you made your parents buy for you as a kid?",
"What topic do you wish was a college major but isn't?",
"Have you ever had an Internet friend?",
"What is your earliest childhood memory? If it’s something 'mundane,' why do you think it stuck in your memory? If it’s something unusual/unique, what do you remember most vividly about it?",
"What is your favorite compliment of all the compliments you've ever received?",
"What are you looking forward to right now?",
"What would you write on a gigantic billboard?",
"What random stranger from your life do you think about or (even talk about) regularly?",
"What famous masterpiece painting or sculpture would you like to own?",
"If you went into the witness protection plan what identify would you like to assume?",
"What is a boring fact about yourself?",
"If you had to survive as a fruit, what would it be?",
"Dark question, but what song would you like to be played at your funeral?",
"Which book did you read in college or high school that was actually interesting enough that you still think or talk about it sometimes?",
"If you had one opportunity to permanently change someone's life (better or worse) who would it be and how would you change it?",
"Without using the title of your job, tell me what you do.",
"What’s something you would not tell someone about yourself on a first date?",
"If you could rename yourself, what new name would you choose, and why?",
"What’s the most expensive habit you’ve started as an adult that you now wish you could break?",
"What was the first R-rated movie you saw? How old were you?",
"What was your first concert? How did you get there?",
"What is your favorite body of water? Why?",
"If you had to make your own zombie movie, what would your zombies be like? How would they be different from stereotypical zombies? How would they be similar?",
"What’s something new you’ve learned about yourself in the last three months?",
"Have you been pleasantly surprised by anything recently?",
"Have you had any unanticipated quarantine-specific cravings for comfort foods (and if so, what)? Have you rediscovered any old passions?",
"If you had to describe how you're feeling right now as a weather pattern, what's your forecast?",
"What’s the worst prediction you ever made?",
"If you could sing like any famous singer in the world (living or dead), who would it be?",
"Describe something that’s made you smile today.",
"What’s one word you would use to describe yourself as a teenager?",
"What material are you most like? (E.g., plastic, porcelain, dirt, silk, stone etc.)",
"If you did not have to sleep, how would you spend the extra 8 hours?",
"If you weren't doing your current job, what would your dream job be?",
"What thing from nature are you?",
"What would you do if I gave you a billion dollars?",
"If you could do something that you don’t do because it’s bad for you, but you could do it without any repercussions — what would you do?",
"Have you ever quit doing something that you used to be really passionate about? Do you regret it? Or are you happy you quit? Either way: Do you think you’ll ever take it up again?",
"Imagine you could devote a year to researching someone’s biography. Who would your subject be?",
"If you had to take a bath in a food, which food would it be?",
"What question do you wish people would ask you?",
"Of the places you have lived or spent significant time, which one had the most pleasing view out the front door/main window/etc for you and why?",
"Who is your pick for the most underrated character in a movie or TV show?",
"Tell me about a time when you changed your mind.",
"If you're going to win the lottery, would you rather win $10 million, or $100 million?",
"Imagine you are backpacking through a remote jungle and the guide you are with has you spend the night with a native tribe. During the evening they treat you as if you were their guest of honor. They put on a show for you and cook you a giant feast . . . part of which includes human flesh. A delicacy for them. Would you eat it? Or, at the very least, would you be curious to know what it tasted like?",
"If you could live in the setting of any book or movie, without necessarily being involved in the story, which would you choose?",
"If you could be one other person, who would that person be and why?",
"What is your oldest or most cherished grudge?",
"What is your earliest memory?",
"Tell me something about yourself that I could never tell from looking at you.",
"If you could own one building, any building, what would it be?",
"If you could only use three condiments for the rest of your life, what would they be?",
"What is your secret skill?",
"If you could say one sentence to your pet and know they would understand it, what would you say?",
"Tell me about something you love doing that you’re terrible at. And tell me about something you really do not like doing that you’re great at.",
"Would you rather be able to speak every language in the world fluently, or be able to play every musical instrument as well as a virtuoso?",
"If you could safely eat any inedible object, what would it be?",
"What are you into now that you never thought you would be into? And conversely, What’s something you used to be into that you’re not anymore?",
"To start such a gathering, have all participants go around the room and describe how they got their names. That gets them talking about their family, puts them in a long-term frame of mind and illustrates that most people share the same essential values.",
"What is a supposedly fun thing that you did — that you’ll never do again?",
"If you had unlimited resources, what frivolous thing would you collect? Not books. It has to be frivolous.",
"What is something you didn’t like but you are glad happened?",
"Let another player post a status on your social.",
"Do freestyle rap for 1 minute about the other participants.",
"Do an impression of another player until someone can figure out who it is.",
"Dance with no music for 1 minute.",
"Do a cartwheel.",
"Let the person on your right draw on your face.",
"Drink lemon juice.",
"Crack an egg on our head.",
"Act like a chicken until your next turn.",
"Burp the alphabet.",
"Talk in an accent of your choice until your next turn.",
"Call a friend, pretend it’s their birthday, and sing “Happy Birthday” to them.",
"Perform ballet for 1 minute.",
"Shower with your clothes on.",
"Take a selfie on the toilet and post it.",
"End each sentence with the word “not” until your next turn.",
"Name a famous person that looks like each player.",
"Dance like your life depends on it.",
"Eat a packet of hot sauce or ketchup straight.",
"Spin around 12 times and try to walk straight.",
"Put on a blindfold and touch the other players’ faces until you can figure out who it is.",
"Let the other players redo your hairstyle.",
"Eat a raw egg.",
"Let the player to your right redo your makeup.",
"Pretend to be a squirrel until your next turn.",
"Dump a bucket of cold water on your head.",
"Lick a bar of soap.",
"Eat a teaspoon of mustard.",
"Talk without closing your mouth.",
"You have 5 minutes to write a country song and perform it.",
"Let someone paint your nails any way they want.",
"Quack like a duck instead of speaking until your next turn",
"Sing the national anthem in a British accent.",
"Show the most embarrassing photo on your phone.",
"Let the rest of the group DM a celebity from your Instagram account.",
"Keep your eyes closed until it’s your go again.",
"Bite into an onion (or other fruit/veggie) like an apple",
"Keep three ice cubes in your mouth until they melt.",
"Yell out the first word that comes to your mind.",
"Eat a spoonful of mustard.",
"Try to lick your elbow.",
"Try to drink a glass of water while standing on your hands.",
"Say two honest things about everyone else in the group.",
"Put as many snacks into your mouth at once as you can.",
"Try and make the group laugh as quickly as possible.",
"Post the oldest selfie on your phone on Instagram Stories.",
"Do four cartwheels in a row.",
"Howl like a wolf.",
"Dance without music for one minute.",
"Do the worm.",
"Sell a piece of trash to someone in the group using your best salesmanship.",
"Imitate a celebrity every time you talk.",
"Hold a funny face for the rest of the round.",
"Sit in a spinning chair and have the group spin you for 30 seconds.",
"Dance with no music for 1 minute.",
"Imitate popular YouTube videos until someone can guess the video you are imitating.",
"Make up a 30-second opera about a person or people in the group and perform it."];

var notsober = ["Can you daydream at night?", "Which came first, the plant or the seed?",
"If actions speak louder than words, is speaking also an action?",
"Does being “up” for something mean the same thing as being “down” for something?",
"What time is it not?",
"If you try to fail, but end up succeeding, which did you actually do?",
"Who created God?",
"What's the highest thing you've ever done?",
"Is getting high and remembering something from your past simply time travel?",
"Which scientists, philosophers, and researchers were high when they made their most important and noteworthy discoveries?",
"Who was the first person that saw cannabis and decided to smoke it?",
"If you smoke weed on a boat, does that make it seaweed?",
"If you drop soap on the floor, is the floor clean or is the soap dirty?",
"Is the “s” or the “c” silent in “scent”?",
"If money is the root of all evil, why do they ask for it in church?",
"If you clean a vacuum, do you become a vacuum cleaner?",
"What does water taste like?",
"Can dogs get a song stuck in their head?",
"When was the last time you peed in bed?",
"What is the biggest lie you have ever told?",
"Tell us your most embarrassing vomit story.",
"Have you ever made out with someone here?",
"Have you ever cheated or been cheated on?",
"What are your top three turn-ons?",
"What is your deepest darkest fear?",
"What is the most childish thing you still do?",
"What is something your friends would never expect that you do?",
"Who is the person you most regret kissing?",
"When was the last time you lied?",
"Who was the last person you licked?",
"What is the most embarrassing picture of you?",
"What’s the most embarrassing thing you’ve ever done?",
"Have you ever broken the law?",
"Do you have any fetishes?",
"What’s the worst thing you’ve ever done?",
"What’s the worst thing you’ve ever said to anyone?",
"What’s the biggest misconception about you?",
"What’s a secret you’ve never told anyone?",
"What would you do if you were the opposite sex for a week?",
"What’s the worst time you let someone take the blame for something you did?",
"What do most people think is true about you, but isn’t?",
"What’s your biggest regret?",
"What are your thoughts on polyamory?",
"What is the biggest thing you’ve gotten away with?",
"Why did you break up with your last boyfriend or girlfriend?",
"What is the most embarrassing series of texts you have on your phone?",
"When was the last time you cried?",
"What’s your biggest fantasy?",
"Tell me about your first kiss",
"What is the most embarrassing thing in your room?",
"What was the most awkward romantic encounter you have had?",
"Do you have a hidden talent?",
"What is the stupidest thing you have ever done?",
"What pictures or videos of you do you wish didn’t exist?",
"What is your biggest regret?",
"Who is your crush?",
"Tell me about your most awkward date.",
"What is the naughtiest thing you’ve done in public?",
"What is the most expensive thing you have stolen?",
"What’s something you’re glad your mum doesn’t know about you?",
"What is something that people think you would never be into, but you are?",
"Who was your first celebrity crush?",
"Have you ever cheated in an exam?",
"What’s the drunkest you’ve ever been?",
"What is the silliest thing you have an emotional attachment to?",
"What’s the biggest mistake you’ve ever made?",
"What’s the most disgusting thing you’ve ever done?",
"Who would you like to kiss in this room?",
"Where’s the weirdest place you’ve had sex?",
"What’s the worst thing anyone’s ever done to you?",
"What’s your worst habit?",
"What’s the strangest dream you’ve had?",
"Have you ever been caught doing something you shouldn’t have?",
"What’s the worst date you’ve been on?",
"Have you ever lied to get out of a bad date?",
"Have you ever peed in the shower?",
"Have you ever shit yourself since you were a child?",
"What is the most embarrassing thing your parents have caught you doing?",
"What’s the most trouble you’ve been in?",
"What secret about yourself did you tell someone in confidence and then they told a lot of other people?",
"When was the most inappropriate time you farted?",
"What is the scariest dream you have ever had?",
"What is the grossest thing that has come out of your body?",
"What is your favourite thing that your boyfriend or girlfriend does?",
"Who have you loved but they didn’t love you back?",
"If you starred in a romance, what would it be like?",
"What was the cruellest joke you played on someone?",
"What is the most embarrassing thing you have put up on social media?",
"What is the grossest thing you have had in your mouth?",
"Tell me about the last time someone unexpectedly walked in on you while you were naked.",
"What is the most embarrassing nickname you have ever had?",
"Describe your most recent romantic encounter in detail.",
"What is the weirdest thing you have done for a boyfriend or girlfriend?",
"Is it true that you (whatever you or the group suspects they do/did)?",
"When was the last time you wiped a booger off on something that shouldn’t have boogers on it?",
"What do you really hope your parents never find out about?",
"Tell me something you don’t want me to know.",
"What have you done that people here would judge you most for doing?",
"What is something that you have never told anyone?",
"What is the most disgusting habit you have?",
"Give a foot massage to the person on your right.",
"Say something dirty to the person on your left.",
"Eat a banana without using your hands.",
"Twerk for a minute.",
"Like the first 15 posts on your Facebook newsfeed.",
"Give a lap dance to someone of your choice.",
"Show off your orgasm face.",
"Empty out your wallet/purse and show everyone what’s inside.",
"Show the last five people you texted and what the messages said.",
"Try to put your whole fist in your mouth.",
"Remove four items of clothing.",
"Put 10 different available liquids into a cup and drink it.",
"Do your best impression of a baby being born.",
"Pretend to be the person to your right for 10 minutes.",
"Do your best sexy crawl.",
"Let someone shave part of your body.",
"Tell everyone an embarrassing story about yourself.",
"Tell the saddest story you know.",
"Belly dance like your life depended on it.",
"Curse like sailor for 20 seconds straight.",
"Pole dance with an imaginary pole.",
"Let someone else tickle you and try not to laugh.",
"Serenade the person to your right.",
"Talk in an accent for the next 3 rounds.",
"Make every person in the group smile, keep going until everyone has cracked a smile.",
"Kiss the person to your left.",
"Attempt to do a magic trick.",
"Eat five tablespoons of a condiment.",
"Attempt to breakdance for one minute.",
"Let the group give you a new hairstyle.",
"Take a shower with your clothes on.",
"Break two eggs on your head.",
"Attempt to walk on your hands for as far as you can.",
"Try to juggle 2 or 3 items of the group’s choosing.",
"Gargle something that shouldn’t be gargled, but won’t hurt you.",
"Get slapped on the face by the person of your choosing.",
"Spin an imaginary hula hoop around your waist for the rest of the round.",
"Choose someone in the group. How would you seduce them?",
"Compose a poem on the spot based on something the group comes up with.",
"Pole dance for 1 minute with an imaginary pole.",
"Choose someone from the group to give you a spanking.",
"Post an extremely unflattering picture of yourself to the social media outlet of your choosing.",
"Imagine something in your room. Now spell it with your nose and keep spelling it with your nose until someone from the group guesses what you are trying to spell.",
"After the group chooses one rude word, sing a song and insert that rude word once into every line of the song.",
"Drag your butt on the carpet like a dog from one end of the room to the other.",
"Open a bag of snacks or candy using only your mouth, no hands or feet.",
"Bend at the waist so that you are looking behind you between your legs. Now run backwards until you can tag someone with your butt.",
"Go to the bathroom, take off your underwear and put it on your head. Wear it on your head for the rest of the game.",
"Act like whatever animal someone yells out for the next 1 minute.",
"Eat one teaspoon of the spiciest thing you have in the kitchen.",
"Transfer an ice cube from your mouth to the person’s mouth on your right.",
"Call the 3rd contact on your phone and sing them 30 seconds of a song that the group chooses.No talking.",
"Pretend to be a food. Don’t pretend to eat the food, pretend to be the food. Keep pretending until someone in the group guesses the food you are.",
"Drop something in the toilet and then reach in to get it.",
"Find the person whose first name has the same letter as your first name or whoever’s first name’s first letter is closest to yours. Now lick their face.",
"Jump up and down as high as you can go for a full minute.",
"Let two people give you a wet willy at the same time.",
"Sing a praise song about a person of the groups choosing.",
"Depict a human life through interpretive dance.",
"Write something embarrassing somewhere on your body (that can be hidden with clothing) with a permanent marker.",
"Beg and plead the person to your right not to leave you for that other boy or girl.",
"Put ice cubes down your pants.",
"Stick your arm into the trash can past your elbow.",
"Lick the floor.",
"Switch clothes with someone of the opposite sex in the group for three rounds.",
"Let the group pose you in an embarrassing position and take a picture.",
"Give someone your phone and let them send one text to anyone in your contacts.",
"Let the group look through your phone for one minute.",
"Drink a small cup of a concoction that the group makes.",
"Let the person to your left draw on your face with a pen.",
"Grab a trash can and make a hoop with your hands above the trash can. Have other members of the group try to shoot trash through your hoop.",
"Do pushups until you can’t do any more. If none, same.",
"Swap clothes with someone for 2 rounds.",];																							

var soberrange = sober.length;
var notsoberrange = notsober.length;
var vibe;

// $('#vibetoggle').change(function(){
//   if ($(this).is(':checked')) {
// 	vibe.push("checked");
//   } else {
// 	vibe.push("unchecked");
// 	};
// })

// currentvibe= console.log(vibe[vibe.length - 1]);

// if (currentvibe == 'checked'){
// $("#launch").click(function(){
//   var soberindex = Math.floor(Math.random() * soberrange);
//   var soberprompt= sober[soberindex];
//     $("#theprompt").html(soberprompt);
// })
// } else {
// $("#launch").click(function(){
//   var notsoberindex = Math.floor(Math.random() * notsoberrange);
//   var notsoberprompt= notsober[notsoberindex];
//     $("#theprompt").html(notsoberprompt);
// });
// }

$("#launch").click(function(){

	console.log("click");

	var current_vibe = document.querySelector('#vibetoggle');

	console.log(current_vibe.checked);

   if (current_vibe.checked == false) {
   	var soberindex = Math.floor(Math.random() * soberrange);
  	var soberprompt= sober[soberindex];
    $("#theprompt").html(soberprompt);
    console.log("sober");
   } else {
   	var notsoberindex = Math.floor(Math.random() * notsoberrange);
  	var notsoberprompt= notsober[notsoberindex];
    $("#theprompt").html(notsoberprompt);
    console.log("notsober");
   }
  
});



